### PR TITLE
Feature/blocks

### PR DESCRIPTION
**Pull request by uselessSABOTAGE**
Hi!

I saw this on Reddit and am ecstatic about this. Are you able to add in the blocks to the mod? 

Thanks!

### CODE REVIEW

**Comment by samolego** [comment]
They'll come, first I need to add other blocks & the client models.

**Comment by samolego** [comment]
If you want to play around with them, you can build the jar yourself, however, current blocks might be incompatible with the ones in release. (As I might change some nbt saving stuff)

**Comment by uselessSABOTAGE** [comment]
Thanks for responding.  I will wait until you complete it.  Do you have a timeline?

**Comment by samolego** [comment]
Timeline as ETA? No.

**Comment by uselessSABOTAGE** [comment]
Yes, and ok, thank you for responding.

**Pull request closed without merging**
