### PR TITLE
Fix IronFarmBlockEntity#produceIron method

### PR DESCRIPTION
**Pull request by Supernich**
It was crashing because minecraft LootContext.Builder#create changed interface and expects Optional instead of Nullable

Bump minecraft version to 1.20.4

Bump fabric version to latest

Bump dependencies versions to latest

### CODE REVIEW

**Comment by Supernich** [comment]
Fix for #30

**Comment by samolego** [comment]
Thanks for contributing!

**Comment by samolego** [comment]
Did it build on your machine?

**Comment by Supernich** [comment]
I didn't, but i run it in debug and it was ok. Only thing was some warnings that i just ignored.

I'm not familiar with java and it was my first time working with java and minecraft mods.

**Pull request merged**
